### ISSUE TITLE
执行demo （GoogleSearch）错误，报错信息看详情，请教下

### ISSUE THREAD

**Issue by sgjeff** [NetEase/Dagger#51]
Exception in thread "main" java.lang.NoSuchMethodError: org.openqa.selenium.chrome.ChromeDriverService$Builder.usingDriverExecutable(Ljava/io/File;)Lorg/openqa/selenium/remote/service/DriverService$Builder;
    at com.netease.dagger.BrowserEmulator.setupBrowserCoreType(BrowserEmulator.java:71)
    at com.netease.dagger.BrowserEmulator.<init>(BrowserEmulator.java:58)
    at com.tairanchina.taihe.GoogleSearch.main(GoogleSearch.java:11)

**Comment by sgjeff** [comment]
电脑是mac，chromedriver下载的是2.21，chrome版本是 44.0.2403.125 (64-bit)
